server:
  port: 5000

spring:
  profiles:
    active: local
  application:
    name: SSGPOINT_APP

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
      #        show_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true # false 할지 조원과 상의

  data:
    redis:
      host: localhost
      port: 6379

#  batch:
#    initializer-schema: always