server:
  port: 8000

spring:
  application:
    name: SSGPOINT_APP

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3307/ssgpoint
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver